id: IEE7E58B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T15:04:40+00:00'
last_modified: '2022-06-10T04:01:08.672867+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12061
  title: ཕྱག་རྡོར་ཐུགས་ཀྱི་སྙིང་ཁུའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    454F:
      image_group_id: I1KG12065
      title: Volume 1 of phyag rdor thugs kyi snying khu'i skor/
      total_pages: 562
      order: 1
      base_file: 454F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
